---
output:
  pdf_document: default
  html_document: default
---
RMarkdown: MBMS_Analysis_Reliability
Author: Zoe Crawley
Date Created: 02/10/2022
Data: MBMS Phase 1 Data, ZC Honor's Thesis

In this document I will calculate reliability for the following measures: PSS, RYFF, BDI-II, BAI, and PANAS.

```{r}
library(readr)
library(ltm)
library(psych)
library(MBESS)
```

*PSS*
```{r}
#load dataset
#pss_baseline <- read_csv("thesis/reliability/mbms_pssreliability_baseline.csv")
#pss_post <- read_csv("thesis/reliability/mbms_pssreliability_post.csv")
#pss_followup <- read_csv("thesis/reliability/mbms_pssreliability_followup.csv")
```


```{r}
#calculate baseline
cronbach.alpha(pss_baseline)

#calculate post
cronbach.alpha(pss_post)

#calculate follow-up
cronbach.alpha(pss_followup)

```

*RYFF*
```{r}
#load dataset#
#ryff_baseline <- read_csv("thesis/reliability/mbms_ryffreliability_baseline.csv")
#ryff_post <- read_csv("thesis/reliability/mbms_ryffreliability_post.csv")
#ryff_followup <- read_csv("thesis/reliability/mbms_ryffreliability_followup.csv")
```

```{r}
#calculate baseline
cronbach.alpha(ryff_baseline)

#calculate post
cronbach.alpha(ryff_post)

#calculate follow-up
cronbach.alpha(ryff_followup)
```
*BDI*
```{r}
#load dataset 
#bdi_baseline <- read_csv("thesis/reliability/mbms_bdireliability_baseline.csv")
#bdi_post <- read_csv("thesis/reliability/mbms_bdireliability_post.csv")
#bdi_followup <- read_csv("thesis/reliability/mbms_bdireliability_followup.csv")
```

```{r}
#calculate baseline
cronbach.alpha(bdi_baseline)

#calculate post
cronbach.alpha(bdi_post)

#calculate follow-up
cronbach.alpha(bdi_followup)

```

*BAI*
```{r}
#load dataset#
#bai_baseline <- read_csv("thesis/reliability/mbms_baireliability_baseline.csv")
#bai_post <- read_csv("thesis/reliability/mbms_baireliability_post.csv")
#bai_followup <- read_csv("thesis/reliability/mbms_baireliability_followup.csv")
```

```{r}
#calculate baseline
cronbach.alpha(bai_baseline)

#calculate post
cronbach.alpha(bai_post)

#calculate follow-up
cronbach.alpha(bai_followup)

```
*#PANAS#*
CODE ADAPTED FROM 
multilevel.reliability 

PANAS Start
```{r}
describe(panas_start)
```

```{r}
omega(panas_start[,2:22])
```

```{r}
describe(panas_end)
```

```{r}
omega(panas_end[, 2:22])
```

